name: distribute-debug-apk
run-name: Build by @${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  upload-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v3
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: "${{secrets.sa_64}}"
          filename: "./app/build/outputs/apk/debug/*.apk"
          folderId: "${{secrets.gd_folder}}"