name: distribute-debug-apk
run-name: Build by @${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  build-debug-apk:
    name: Generate debug apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build debug apk
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
  upload-debug-apk:
    needs: build-debug-apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v3
      - name: Download apk
        uses: actions/download-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: "${{secrets.sa_64}}"
          filename: "./app/build/outputs/apk/debug/*.apk"
          folderId: "${{secrets.gd_folder}}"